### ISSUE TITLE
[week 2] continuous distributed representation의 의미

### ISSUE THREAD

**Issue by HanNayeoniee** [kimcando/BoostcampAITech3-PaperReading-Embedding#12]
본 논문은 sparse representation의 단점을 보완하고자 새로운 두 가지 distributed representation인 CBOW와 Skip-gram을 제안하는데요, **continuous distributed representation**과 distributed representation은 다른 의미인가요?

논문에서는 둘을 구분해서 사용하는 것 같지는 않은데, 동일한 의미인지 궁금합니다.
다른 의미라면 continuous 하다는게 벡터 안의 값이 continuous한 것일까요? 아니면 입력으로 continuous 단어들을 받는다는 의미일까요?

**Comment by kimcando** [comment]
[Quora](https://www.quora.com/What%E2%80%99s-the-difference-between-continuous-representation-and-distributed-representation) 검색을 참조해보았습니다.ㅎㅎ
* continuous representation : 수치적 representation을 real number와 같은 continuous domain으로 표현한 것이구요. 그 값자체는 single scalar나 scalar의 벡터등으로 표현될 수 있습니다.
* distributed representation : 어떤 representation 을 value의 벡터형으로 나타낼 수 있는 것을 의미합니다.

결국 연속된 value를 벡터형으로 나타내어 real valued dense vector 꼴로 단어를 나타내는걸로 보시면 될 것 같아요! 덕분에 엄밀하게 찾아봤네요 나연님 좋은 질문 감사해용
