### ISSUE TITLE
[week3] Noise Contrastive Estimation (NCE)란 무엇일까?

### ISSUE THREAD

**Issue by TB2715** [kimcando/BoostcampAITech3-PaperReading-Embedding#14]
1. Introduction, 2페이지 상단에 

> In addition, we present a simplified variant of **_Noise Contrastive Estimation (NCE)_** [4] for training the Skip-gram model that results in faster training and better vector representations for frequent words, compared to more complex hierarchical softmax that was used in the prior work [8].

라고 Noise Contrastive Estimation(NCE) 개념이 등장합니다. NCE란 어떤 개념일까요?

**Comment by kimcando** [comment]
현지님 제가 논문을 아직 읽지도 못했곸ㅋㅋㅋ그래서 이슈만 봤는데.. relational extraction 찾아보니까 또 저 워딩이 나오네요. 설명해주셨듯 단어 갯수가 많을 때 뭔가 샘플링이 필요할 때 쓰는 방식인가보네요
![image](https://user-images.githubusercontent.com/40655873/159533240-5c15366a-e853-4dc4-829c-4cedb59f6b4a.png)

**Comment by kimcando** [comment]
아아 논문 읽고 다시보니까 좀더 이해가 되는데 아래 부분이 이해가 안돼서 고민해봐야할 것 같아요 ㅠ
>일반적으로 단어 개수가 많을 때 사용하고, NCE를 사용할 경우 문제를 (실제 분포에서 얻은 샘플)과 (인공적으로 만든 답음 분포에서 얻은 샘플)을 구별하는 이진 분류 문제로 바꿀 수 있음

**Comment by sujeongim** [comment]
http://incredible.ai/nlp/2017/11/25/Word2Vec-Noise-Constrastive-Estimation/
해당 링크가 설명을 좀 자세히 해둔 것 같습니다!
저도 아직 제대로 못 읽어보긴 했는데..ㅠㅜ
읽고 이해되면 추가 댓글 달겠습니다..!
