### ISSUE TITLE
[Week3] Numerical Probability는 무엇일까?

### ISSUE THREAD

**Issue by sujeongim** [kimcando/BoostcampAITech3-PaperReading-Embedding#17]
논문에서 Negative Sampling은 NCE를 단순화한 방식이라고 합니다. 
이 둘의 가장 큰 차이점에 대해서 논문은 아래와 같이 설명했는데요, 

The main difference between the Negative sampling and NCE is that NCE needs both
samples and the **numerical probabilities** of the noise distribution, while Negative sampling uses only
samples. And while NCE approximately maximizes the log probability of the softmax, this property
is not important for our application.

여기에서 Negative Sampling에서는 필요하지 않은 것이 numerical probability라고 하는데, 
이 numerical probability의 의미가 무엇인지 잘 모르겠습니다. 
정확히 말하면 NCE에서 NEG로 단순화하는 과정에서 무엇이 빠졌다는 것인지 잘 모르겠습니다..!

**Comment by cow-coding** [comment]
추천 시스템 트랙 RecSys 강의 5강 Item2Vec and ANN - (1) Word2Vec 에서 SGNS 관련 설명이 있습니다.
물론 main이 word2vec이 아니라 엄청 자세히는 잡아주시지 않지만....

**Comment by kimcando** [comment]
* doc2vec의 코드에서 noise distribution 참고?
