### ISSUE TITLE
[week1] loss in average mutual information?

### ISSUE THREAD

**Issue by kimcando** [kimcando/BoostcampAITech3-PaperReading-Embedding#2]
mutual information과 loss in average mutual information과 다른점 ?
loss in average MI가 적은애들을 merge한다라는게 비슷한 의미를 가진 단어끼리 merge한다라고 해석하는게 맞나? 
MI가 두 단어의 상관성을 나타내고, 비슷한 의미의 단어끼리 같은 클래스로 merge해야하기 때문에 MI가 큰 애들끼리는 묶어야한다고 이해할 수 있는데 loss in average MI가 적은애들끼리 merge한다고 해서 잘 이해가 안됨.

[논문](https://aclanthology.org/J92-4003.pdf)의 473page 두번째 문단에 정의는 돼있는데 \I_k, \I_k(i,j)의 정의에 대한 전개가 위에 쭉 있는데 그걸 놓쳐서 정확하게 이해를 못하겠음. \I_{k-1} = \I_k(i,j) 로 연결지어 생각했을 때 k 번째 sequence의 페어 i,j의 MI에서 (k-1)번째 sequence의 페어 i,j페어 의 MI를 뺀 값?으로 생각할 수 있는 것 같은데..

**Comment by sujeongim** [comment]
소연님 깃허브에서 수식 쓰는 법을 잘 몰라서..ㅜ 적다가 도저히 시간 안에 못 적을 것 같아서 아직 적고 있는 블로그 글 링크를 남깁니다...이따 다시 수식 정리해서 여기에 올리겠습니다!
소연님 질문에 대해 제가 이해한 부분만 정리해보았습니다. 나중에 다시 올릴 때 소연님 이름은 지우도록 하겠습니다!
https://velog.io/@sujeongim/%EB%85%BC%EB%AC%B8-NLP-n-gram
