### ISSUE TITLE
[week1] discussion동안 나온 질문

### ISSUE THREAD

**Issue by kimcando** [kimcando/BoostcampAITech3-PaperReading-Embedding#3]
* notation 에서 혼동옴 : small t 와 large T 가 의미하는 것과 n, n-1이 의미하는 것의 차이?
* bleu score에서 나온 n-gram과 본 논문이 제안하는 n-gram class model이 연관성이 있나?

**Comment by idj7183** [comment]
N-gram이라는 것 자체가 주변 단어와의 관계를 파악하기 위한 수단 중의 하나인 것 같습니다.
본 논문이 제안하는 n-gram class Model은 이런 수단을 활용하는 Model인 것이고, BLEU score는 N-gram이라는 수단을 활용한 점수인 것 같습니다.

N-gram은 단순히 cm 같은 단위 지표이고, 우연히 BLEU와 N-gram Class Model은 그 단위 지표를 활용할 뿐인 것 같습니다.

N-gram = cm라고 생각하면, BLEU는 두 사람이 앉은 거리를 cm를 활용해 재는 것, Model은 두 사람이 앉은 거리를 cm로 재서 두 사람의 친밀도를 반환하는 Function이 될 것 같습니다
