### ISSUE TITLE
[week2] hierarchical softmax가 뭘까요?

### ISSUE THREAD

**Issue by angieKang** [kimcando/BoostcampAITech3-PaperReading-Embedding#5]
어휘의  이진 트리 표현으로 검증되어야 하는 결과값의 크기가 log_2(V)에 가깝게 작아질 수 있다고 하는데 어떤 방식으로 이렇게 되는 걸까요?

3p, 'With binary tree representations of the vocabulary, the number of output units that need to be evaluated can go down to around $log_2(V)$.'
'the term H x V can be efficiently reduced to H x log_2(V) by using hierarchical softmax.'

**Comment by kimcando** [comment]
저도 궁금해서 내일찾아보려구요ㅎㅎㅎㅎ

**Comment by HanNayeoniee** [comment]
저도 아직 찾아보고 있는 중이지만, 제가 이해한 부분까지만 설명하겠습니다.

이전까지 사용했던 softmax는 1층으로 구성되어 다음단어의 확률을 구할 때 노드 V개의 확률값을 계산해야 하지만, hierarchical softmax는 허프만 코딩을 사용해 log_2(V)개의 확률값만 계산하면 된다고 합니다.
여기서 허프만 코딩은 **이진 트리**를 사용해 단어 등장 빈도수에 따라 다른 길이의 코드를 부여하는 압축방식(?) 이라고 생각하시면 될 것 같습니다.

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/33839093/158714044-f6609255-4e08-4958-be6f-b58a560f4080.png">

위의 그림에서 왼쪽은 일반 softmax, 오른쪽은 hierarchical softmax를 나타낸 모습입니다. 
다음 단어 "I'm"이 올 확률을 구할 때 softmax 방식에서는 모든 단어 8개의 확률을 구해야 하지만, hierarchical softmax을 사용하면 root node부터 "I'm" leaf node까지의 경로에 위치만 3개 단어에 대한 확률만 필요합니다.
V=8 일 때, 계산 복잡도가 V -> log_2(V)로 감소한 것을 확인할 수 있습니다. 

[그림 출처](https://soundprovider.tistory.com/entry/%EC%97%B0%EA%B5%AC-%EB%B6%84%EB%A5%98-Class%EA%B0%80-%EB%A7%8E%EC%9D%84-%EB%95%8C-Softmax-%EA%B0%9C%EC%84%A0-%EB%B0%A9%EB%B2%95)

[참고 포스팅 1](https://uponthesky.tistory.com/15)

[참고 포스팅 2](http://solarisailab.com/archives/959)

**Comment by HanNayeoniee** [comment]
[DSBA랩 논문리뷰](https://www.youtube.com/watch?v=sidPSG-EVDo) 19분~ 부분에 hierarchical softmax 수식이랑 자세한 설명 나와있어요!
